### ISSUE TITLE
Cannot unregister FacilityManager callbacks

### ISSUE THREAD

**Issue by d09** [jai-imageio/jai-imageio-jpeg2000#3]
jj2000.j2k.util.FacilityManager has a couple of static hashtables used for callbacks. You can add entries to these hashtables but not remove them, this will cause a memory leak eventually.

Here is a proposed patch that fixes the problem:

--- src/main/java/jj2000/j2k/util/FacilityManager.java~ 2015-03-16 13:56:55.000000000 +0000
+++ src/main/java/jj2000/j2k/util/FacilityManager.java  2015-04-01 10:50:03.000000000 +0100
@@ -101,6 +101,14 @@
         }
     }
 
+    public static void unregisterProgressWatch(Thread t) {
+        if (t == null) {
+            defWatchProg = null;
+        } else {
+            watchProgList.remove(t);
+        }
+    }
+
     /** 
      * Returns the ProgressWatch instance registered with the current
      * thread (the thread that calls this method). If the current
@@ -135,6 +143,14 @@
         }
     }
 
+    public static void unregisterMsgLogger(Thread t) {
+        if (t == null) {
+            defMsgLogger = null;
+        } else {
+            loggerList.remove(t);
+        }
+    }
+
     /**
      * Returns the MsgLogger registered with the current thread (the
      * thread that calls this method). If the current thread has no registered

**Comment by stain** [comment]
Thanks, I've incorporated this and [modified unregisterMsgLogger](https://github.com/jai-imageio/jai-imageio-jpeg2000/commit/630a5bcc62399d0a94d06111823fc1b23e911a25) to reset to the default System.out logger as I don't think callers handle null-loggers.  (Really these should be changed for java.util.logging I guess)

A `ThreadLocal` might have been better choice here - but as the current register methods takes the Thread as an argument that would break the old API (you can't set another thread's ThreadLocal).

**Comment by stain** [comment]
If you could test it for me, (or add a test case? Perhaps tricky..) then I can release this as a new patch version to Maven Central.
