### ISSUE TITLE
why didn't update until now?

### ISSUE THREAD

**Issue by king1991888** [jai-imageio/jai-imageio-jpeg2000#31]
your project version in maven center repository is 1.3.0. but it is not the lastest version. this version has a bug about "black stain" ,so please update your project version to maven center repository.that will be easier to use more. don't you?

**Comment by Lonzak** [comment]
Please release Version 1.3.1 - many people are eagerly waiting for this...

**Comment by Lonzak** [comment]
5 year birthday after the last release :-)

@stain @rleigh-codelibre @Jugen @glenhein 

I don't know who of you can issue a release (1.3.1 or 1.4) but many people are waiting for this. If you need help please tell us.
https://github.com/jai-imageio/jai-imageio-jpeg2000/issues/28
https://github.com/jai-imageio/jai-imageio-jpeg2000/issues/24
... and many more.

Thanks guys for understanding

**Comment by Lonzak** [comment]
@stain @rleigh-codelibre @Jugen @glenhein
I hope you are fine. We would highly appreciate if you could say something....

Give me access to the repo for 5min and I can press the release button for you ;-)

**Comment by rleigh-codelibre** [comment]
I'm not currently employed in any jpeg2000-related activities, and I voluntarily left the project since I'm not actively participating.  I'm afraid I won't be able to help out.

**Comment by Lonzak** [comment]
Thank you for your answer! This is the first sign of life here :-) even though you are not part of the project anymore. Do you know who is? I think Stian and?

**Comment by rleigh-codelibre** [comment]
I would think @stain is the owner and responsible for it overall, but I am afraid I'm not the best person to ask since I don't actually know the answer.

**Comment by Lonzak** [comment]
Finally - contact has been established :-) A new RC is coming

**Comment by Lonzak** [comment]
A new version 1.4.0 was finally released. Many thanks to stian!

**Comment by stain** [comment]
See https://github.com/jai-imageio/jai-imageio-jpeg2000/releases/tag/jai-imageio-jpeg2000-1.4.0 for release details. It should be mirrored to in Maven Central in a few hours, see BinTray details for alternate Maven repo.

Looking for volunteers that are willing to be release manager in the future - it's basically just `mvn release:prepare` and `mvn release:perform` and then clicking the buttons in BinTray and https://oss.sonatype.org/ - let me know your username on both sides and I can grant access.

**Comment by stain** [comment]
Thanks to @Lonzak for pinging me over the years - I should really have resigned as well as I am struggling to find time to spin up Maven skills. I've seen several open source Maven projects struggle on the release ceremony. 

We wrote a guide for this in Taverna https://taverna.incubator.apache.org/community/releasing - which should work mostly the same here, except we won't need to make the formal release candidates. Still publishing with Maven Central is a bit more work than you may be used to with npm or pypi - so I'm happy to do a Zoom walk-through of a dummy release for anyone volunteering to be Release Manager! Thanks to @Lonzak for testing the 1.4.0 RC!
