### ISSUE TITLE
Incompatible jj2000 libraries

### ISSUE THREAD

**Issue by nightcrawler-** [jai-imageio/jai-imageio-jpeg2000#5]
Please include the jj2000 library you used for this project

**Comment by stain** [comment]
The jj2000 reference library was included in the `jj2000`` package under [src/main/java/jj2000/j2k](https://github.com/jai-imageio/jai-imageio-jpeg2000/tree/master/src/main/java/jj2000/j2k) which reflects upstream [src/share/classes/jj2000/j2k](https://java.net/projects/jai-imageio-core/sources/svn/show/trunk/src/share/classes/jj2000/j2k?rev=254) in [jai-imageio-core from java.net](https://java.net/projects/jai-imageio-core/) -- I am not sure which version of the reference library was used by Oracle.

What is the incompatibility? Is it the package name `jj2000` clashing with the actual reference library? Perhaps it could be moved to the package `com.github.jaiimageio.jpeg2000.impl.jj2000` - but this might not be permitted by the [restrictive JPEG2000 license](https://github.com/jai-imageio/jai-imageio-jpeg2000/blob/master/LICENSE-JJ2000.txt).
